//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vueling.Aplication.Services {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vueling.Aplication.Services.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a amountInsured.
        /// </summary>
        internal static string AMOUNT {
            get {
                return ResourceManager.GetString("AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a apijson.
        /// </summary>
        internal static string APIJSON {
            get {
                return ResourceManager.GetString("APIJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a clientId.
        /// </summary>
        internal static string CLIENTID {
            get {
                return ResourceManager.GetString("CLIENTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a inceptionDate.
        /// </summary>
        internal static string DATE {
            get {
                return ResourceManager.GetString("DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error caused by trying ArgumentNullException.
        /// </summary>
        internal static string E_ARG {
            get {
                return ResourceManager.GetString("E_ARG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error caused by trying HttpRequestException.
        /// </summary>
        internal static string E_HTTP {
            get {
                return ResourceManager.GetString("E_HTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a installmentPayment.
        /// </summary>
        internal static string PAY {
            get {
                return ResourceManager.GetString("PAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a policies.
        /// </summary>
        internal static string POLICY {
            get {
                return ResourceManager.GetString("POLICY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a uricl.
        /// </summary>
        internal static string URICLI {
            get {
                return ResourceManager.GetString("URICLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a uripo.
        /// </summary>
        internal static string URIPOL {
            get {
                return ResourceManager.GetString("URIPOL", resourceCulture);
            }
        }
    }
}
